document:
  name: Linee Guida Tecnologie e standard per assicurare la sicurezza dell'interoperabilità tramite API dei sistemi informatici

  description:
      Linee Guida Tecnologie e standard per assicurare la sicurezza 
      dell'interoperabilità tramite API dei sistemi informatici
  tags:
    - sicurezza
    - interoperabilità
    - API
    - linee guida